### ISSUE TITLE
TokenMissing with OAuth1 on authorization callback

### ISSUE THREAD

**Issue by jacquesd** [lepture/flask-oauthlib#203]
Hello,
I'm updating the OAuth1 module in my application from Flask-OAuth to Flask-OAuthlib and I am using the contrib client due to some SSL verification issues (see #200).
However I keep having a `TokenMissing` exception when processing the response on the authorization callback. 

My code is very similar to the [twitter example](https://github.com/lepture/flask-oauthlib/blob/master/example/contrib/experiment-client/twitter.py):
```python
@my_provider.tokengetter
def oauth_my_provider_token():
    return session.get('my_provider_oauth_token')


@app.route('/login/', methods=['GET'])
def login():
    callback_uri = url_for('.oauth_authorized', next=request.args.get('next') or request.referrer or None,
                           _external=True)
    return my_provider.authorize(callback_uri)


@app.route('/oauth_authorized/', methods=['GET'])
def oauth_authorized():
    next_url = request.args.get('next') or url_for('routing.index')
    response = my_provider.authorized_response()
    if not response:
        session['unauthorized'] = True
        return redirect(url_for("routing.index"))

    session.permanent = True
    session["my_provider_oauth_token"] = (response.token, response.token_secret)
    session['unauthorized'] = False
    session['my_provider_user'] = response['user_id']
    session['oauth_token_expiration_timestamp'] = response['oauth_token_expiration_timestamp']
    session['oauth_token_ttl'] = int(response['oauth_token_ttl'])
    user_info = get_user_info(response['user_id'])
    session['my_provider_user_name'] = '{} {} {}'.format(user_info.get('title'), user_info.get('first_name'),
                                                         user_info.get('family_name'))
    return redirect(next_url)
```
And here is the trace back of the error:
```python
Traceback (most recent call last):
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jacques/Documents/code/indico-mobile/indicomobile/views/authentication.py", line 40, in oauth_authorized
    response = indico.authorized_response()
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/flask_oauthlib/contrib/client/application.py", line 197, in authorized_response
    response = oauth.parse_authorization_response(request.url)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 321, in parse_authorization_response
    self._populate_attributes(token)
  File "/home/jacques/.virtualenvs/indico-mobile/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 330, in _populate_attributes
    token,
TokenMissing: Response does not contain a token: {u'oauth_verifier': u'qmHRXXTk2VPN75RCeHhs3sKTwduaBj5381kRAAaQ', u'next': u'http://localhost:5000/'}
```

I don't know OAuth1 very well but I had a look at the `OAuth1Application.authorized_response` ([L192](https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/contrib/client/application.py#L192)) and from my understanding it appears that it tries to extract the verifier using requests-oauthlib ([L197](https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/contrib/client/application.py#L197)) first and get the token afterwards ([L211](https://github.com/lepture/flask-oauthlib/blob/master/flask_oauthlib/contrib/client/application.py#L211)) but `parse_authorization_response` of `requests-oauthlib` expects a url with the token already set.
Would it be correct to retrieve the token first and adds it to the url before processing it with request-oauthlib or maybe retrieve the verifier via some other way?

**Comment by jacquesd** [comment]
Small update, replacing `OAuth1Application.authorized_response` with the following code works:
```python
# obtains verifier
verifier = request.args['oauth_verifier']

# restores request token from session
if not my_provider._session_request_token:
    session['unauthorized'] = True
    return redirect(url_for("routing.index"))
request_token, request_token_secret = my_provider._session_request_token
del my_provider._session_request_token

# obtains access token
oauth = my_provider.make_oauth_session(
    resource_owner_key=request_token,
    resource_owner_secret=request_token_secret,
    verifier=verifier)
oauth_tokens = oauth.fetch_access_token(my_provider.access_token_url)
response = OAuth1Response(oauth_tokens)
```
I can provide you with a pull request if you are interested.

**Comment by lepture** [comment]
ping @tonyseek

**Comment by tonyseek** [comment]
@jacquesd 

The [RFC 5849](http://tools.ietf.org/html/rfc5849#page-12) described that the `oauth_token` is a required parameter while the server constructing  callback URI. I guess that is why requests-oauthlib raised the `TokenMissing`.

> The server constructs the request URI by adding the
>    following REQUIRED parameters to the callback URI query component:
> 
>    oauth_token
>          The temporary credentials identifier received from the client.
>    oauth_verifier
>          The verification code.

Storing `oauth_token` in `session` (`_session_request_token`) is useless and nonstandard. I will remove it soon. >_<

**Comment by tonyseek** [comment]
I added a blinker signal named `request_token_fetched` in https://github.com/lepture/flask-oauthlib/pull/205. If you want to fix this issue by patching you could do this:

``` python
from flask import session, request
from flask_oauthlib.contrib.client.signals import request_token_fetched
from oauthlib.common import add_params_to_uri

twitter = oauth.remote_app(
    name='twitter',
    version='1',
    endpoint_url='https://api.twitter.com/1.1/',
    request_token_url='https://api.twitter.com/oauth/request_token',
    access_token_url='https://api.twitter.com/oauth/access_token',
    authorization_url='https://api.twitter.com/oauth/authorize')

@request_token_fetched.connect_via(twitter)
def request_token_compliance_fixes(sender, response):
    session['request_token'] = response['oauth_token']

@app.route('/auth/twitter/callback')
def oauth_twitter_callback():
    # fixes nonstandard oauth1.0a
    if 'oauth_token' not in request.args and \
        'oauth_verifier' in request.args and \
        'request_token' in session:
        request.url = add_params_to_uri(request.url, [('oauth_token', session['request_token'])])

    response = twitter.authorized_response()
    if response:
        return repr({'access_token': response['oauth_token']})
    return 'denied'
```

**Comment by jacquesd** [comment]
@tonyseek
Ok, thanks a lot. I am not quite familiar with OAuth 1, but you are right the provider should send the `oauth_token`.
I had a look at it and it turns out the library used by my provider is a bit outdated and has [this bug](https://github.com/simplegeo/python-oauth2/issues/85) for a while now... It is in the process of being replaced with the flask-oauthlib Oauth2  provider ;)
