### ISSUE TITLE
localhost issue

### ISSUE THREAD

**Issue by ken8203** [lepture/flask-oauthlib#250]
Hi,

I clone the example code, and try it.

Then, I access via "localhost"
```
http://localhost:5000/
http://localhost:5000/client
copy id and secret to client.py
http://localhost:8000
```

It fails with the error message:
```
Invalid response from remote
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jaychung/example-oauth2-server/client.py", line 46, in authorized
    session['remote_oauth'] = (resp['access_token'], '')
TypeError: sequence index must be integer, not 'str'
```

But when I access via "127.0.0.1", it works well...
Is this a bug or a requirement?

Thanks a lot!

**Comment by lepture** [comment]
a requirement
