### ISSUE TITLE
ValueError: Error trying to decode a non urlencoded string. Found invalid characters: {':'}

### ISSUE THREAD

**Issue by Alain1405** [lepture/flask-oauthlib#283]
Querying and endpoint protected with `OAuth2Provider` decorator I get the following:
```
1:34:57 PM web.1  |  Traceback (most recent call last):
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
1:34:57 PM web.1  |      return self.wsgi_app(environ, start_response)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
1:34:57 PM web.1  |      response = self.make_response(self.handle_exception(e))
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_cors/extension.py", line 110, in wrapped_function
1:34:57 PM web.1  |      return cors_after_request(app.make_response(f(*args, **kwargs)))
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_potion/__init__.py", line 141, in _exception_handler
1:34:57 PM web.1  |      return original_handler(e)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
1:34:57 PM web.1  |      reraise(exc_type, exc_value, tb)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
1:34:57 PM web.1  |      raise value
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
1:34:57 PM web.1  |      response = self.full_dispatch_request()
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
1:34:57 PM web.1  |      rv = self.handle_user_exception(e)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_cors/extension.py", line 110, in wrapped_function
1:34:57 PM web.1  |      return cors_after_request(app.make_response(f(*args, **kwargs)))
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_potion/__init__.py", line 141, in _exception_handler
1:34:57 PM web.1  |      return original_handler(e)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
1:34:57 PM web.1  |      reraise(exc_type, exc_value, tb)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
1:34:57 PM web.1  |      raise value
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
1:34:57 PM web.1  |      rv = self.dispatch_request()
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
1:34:57 PM web.1  |      return self.view_functions[rule.endpoint](**req.view_args)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 538, in decorated
1:34:57 PM web.1  |      valid, req = self.verify_request(scopes)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/flask_oauthlib/provider/oauth2.py", line 466, in verify_request
1:34:57 PM web.1  |      uri, http_method, body, headers, scopes
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
1:34:57 PM web.1  |      return f(endpoint, uri, *args, **kwargs)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/oauthlib/oauth2/rfc6749/endpoints/resource.py", line 68, in verify_request
1:34:57 PM web.1  |      request = Request(uri, http_method, body, headers)
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/oauthlib/common.py", line 404, in __init__
1:34:57 PM web.1  |      self._params.update(dict(urldecode(self.uri_query)))
1:34:57 PM web.1  |    File "/Users/alain/code/clients/c/backend/venv-development/lib/python3.4/site-packages/oauthlib/common.py", line 131, in urldecode
1:34:57 PM web.1  |      raise ValueError(error % (set(query) - urlencoded, query))
1:34:57 PM web.1  |  ValueError: Error trying to decode a non urlencoded string. Found invalid characters: {':'} in the string: 'where=%7B%22is_deleted%22:false%7D'. Please ensure the request/response body is x-www-form-urlencoded.
```
but accordingly to [this](http://stackoverflow.com/questions/2053132/is-a-colon-safe-for-friendly-url-use/2053640#2053640) colon is perfectly fine.

**Comment by killpanda** [comment]
yes，same issue
