### ISSUE TITLE
UnicodeDecodeError with gzip content encoding

### ISSUE THREAD

**Issue by Damoun** [lepture/flask-oauthlib#343]
On the Twitch API with python 3.5, I try to request some resource but I get an UnicodeDecodeError in the response parsing.

```
Traceback (most recent call last):
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/damoun/Projects/github.com/dam0un/whitelist/whitelist/apps/users/views.py", line 17, in index
    int(me.data['_id']), current_app.config['TWITCH_CHANNEL_ID']
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask_oauthlib/client.py", line 390, in get
    return self.request(*args, **kwargs)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask_oauthlib/client.py", line 478, in request
    return OAuthResponse(resp, content, self.content_type)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask_oauthlib/client.py", line 166, in __init__
    content_type=content_type,
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask_oauthlib/client.py", line 122, in parse_response
    return json.loads(content)
  File "/home/damoun/.virtualenvs/whitelist/lib/python3.5/site-packages/flask/json.py", line 145, in loads
    s = s.decode(kwargs.pop('encoding', None) or 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

I think it's an issue that occur when the body is gzipped.

```
curl -i 'https://api.twitch.tv/kraken/users/42/subscriptions/42'
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
Content-Length: 96
Server: nginx
Status: 400 Bad Request
X-API-Version: 3
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: 
Access-Control-Allow-Headers: 
Cache-Control: max-age=0, private, must-revalidate
Vary: Accept-Encoding
Content-Encoding: gzip
X-UA-Compatible: IE=Edge,chrome=1
X-Request-Id: 43615b7edc85c33ec165f2df80e5af2b
X-Varnish: 2283111455
X-MH-Cache: rails-varnish-api-aws-0e68bbedecd3a0422; M
Timing-Allow-Origin: https://www.twitch.tv
Date: Wed, 30 Aug 2017 12:42:24 GMT
Connection: keep-alive

���Y�VJ-*R�RrJLJ-,M-.Q*.I,)-V�210-.NLO*WHLQQ(.HMMQ����G
```

**Comment by frol** [comment]
Could you, please, provide a minimal code snippet?

To be honest, it seems to be Twitch issue. Both `wget` and `curl` just show gzip binary while they should automatically decompress the body. Python `requests` works fine, though. It is quite an odd behavior...

**Comment by Damoun** [comment]
Here is a gist to reproduce it https://gist.github.com/Damoun/42a5b48e3b8b1555508e879eeae1c35c
You will need a valid consumer key/secret from [Twitch](https://dev.twitch.tv).

On my curl version, the body is decompressed only if I use `--compress` option.

**Comment by zvodd** [comment]
same issue recently whilst using twitch.tv's oauth (python 3.6)

**Comment by frol** [comment]
Well, `urllib` doesn't implement automatic [transparent] Content-Encoding decompression: https://bugs.python.org/issue1508475. I am not sure how to proceed, but here are two options I see:

1. Use `requests`, which does this automatically
2. Implement decompression manually in the `OAuthRemoteApp.http_request`: https://coderwall.com/p/eyadkg/http-request-response-with-compressed-body-in-python

Given that you can instantiate `OAuthRemoteApp`, the fastest workaround for you would be to override the `http_request` method with the manual decompression implementation. You are welcome to make a PR as well.

**Comment by lepture** [comment]
@Damoun Please consider using https://github.com/lepture/authlib 

With the release of version 0.2, it is stable enough to use the Flask client part. Yes, it is more stable than Flask-OAuthlib.
