### ISSUE TITLE
Session Closing too early

### ISSUE THREAD

**Issue by claygorman** [lepture/flask-oauthlib#354]
Hello,

 I will attempt to explain myself as clearly as I can. I am using the recommended session context manager with SQL alchemy.

http://docs.sqlalchemy.org/en/latest/orm/session_basics.html#when-do-i-construct-a-session-when-do-i-commit-it-and-when-do-i-close-it

I have implemented everything and all works ok. I did have an issue however when I initially started with this

```
@contextmanager
def db_session():
    """Provide a transactional scope around a series of operations.
    Taken from http://docs.sqlalchemy.org/en/latest/orm/session_basics.html.
    This handles rollback and closing of session, so there is no need
    to do that throughout the code. Usage:
    with db_session() as session:
        session.execute(query)
    """
    session = _db_session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        # If i do not comment this below then I get an error
        # session.close()
```

The Error I get from not commenting out sesison.close()

```
curl -X POST \
  'http://localhost:5000/oauth/token?grant_type=client_credentials' \
  -H 'authorization: Basic *omitted*'
```

```
Traceback (most recent call last):
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb) 
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb) 
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask_oauthlib/provider/oauth2.py", line 507, in decorated
    uri, http_method, body, headers, credentials
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 117, in create_token_response
    request, self.default_token_type)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/grant_types/client_credentials.py", line 72, in create_token_response
    self.validate_token_request(request)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/grant_types/client_credentials.py", line 104, in validate_token_request
    if not self.request_validator.authenticate_client(request):
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/flask_oauthlib/provider/oauth2.py", line 664, in authenticate_client
    if hasattr(client, 'client_secret') and client.client_secret != client_secret:
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 598, in get 
    value = state._load_expired(state, passive)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 593, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/Volumes/Storage/Users/claygorman/.pyenv/versions/3.6.2/envs/test-oauth-site/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 757, in load_scalar_attributes
    (state_str(state)))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Client at 0x10393a198> is not bound to a Session; attribute refresh operation cannot proceed
```

Any ideas on why I need to comment out the session.close() would help. I think its due to the load_scalar_attributes trying to reuse a session that's already been closed.

**Comment by lepture** [comment]
How it is related to Flask-OAuthlib?
