### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED from authorized_response()

### ISSUE THREAD

**Issue by dmahugh** [lepture/flask-oauthlib#364]
I have a code sample (sample_flask.py in [this repo](https://github.com/microsoftgraph/python-sample-auth)) that uses Flask-OAuthlib to authenticate to Microsoft Graph (via Azure AD), and it was working fine a few weeks ago but has stopped working. It crashes on [the call to authorized_response()](https://github.com/microsoftgraph/python-sample-auth/blob/master/sample_flask.py#L39), with this error:

**urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>**

I've pasted in the full traceback below. Note that the error is occurring when trying to reach this token endpoint at Azure AD: _https://login.microsoftonline.com/common/oauth2/v2.0/token_

The code has not changed, and it's not clear to me what *has* changed. At first I thought it was a regression, but I've tried running with the exact same Python/Flask/Flask-OAuthlib versions as when it was working for me in the past, and get the same error.

Interested in any thoughts on how to debug this or a workaround. Also interested in feedback of the form "you're using Flask-OAuthlib incorrectly" if that's the case, as I'd like for this to be a sample for anyone who wants to use Flask-OAuthlib with our service.

Thanks!

-------------------------------------- FULL TRACEBACK: --------------------------------------
Traceback (most recent call last):
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\dmahugh\Dropbox\graph\python-sample-auth\sample_flask.py", line 39, in authorized
    response = MSGRAPH.authorized_response()
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask_oauthlib\client.py", line 677, in authorized_response
    data = self.handle_oauth2_response()
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask_oauthlib\client.py", line 643, in handle_oauth2_response
    method=self.access_token_method,
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\site-packages\flask_oauthlib\client.py", line 376, in http_request
    resp = http.urlopen(req)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\dmahugh\AppData\Local\Continuum\Anaconda3\envs\python-sample-auth\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

**Comment by lepture** [comment]
@dmahugh Hi, please try https://github.com/lepture/authlib instead. I'm going to replace Flask-OAuthlib with this project.

**Comment by dmahugh** [comment]
Thanks, I'll try migrating my sample to that and let you know how it goes.
